export default [
  { name: "A", include: false, checked: false },
  { name: "B", include: false, checked: false },
  { name: "C", include: false, checked: false },
  { name: "D", include: false, checked: false },
  { name: "E", include: false, checked: false },
  { name: "F", include: false, checked: false },
  { name: "G", include: false, checked: false },
  { name: "H", include: false, checked: false },
  { name: "I", include: false, checked: false },
  { name: "J", include: false, checked: false },
  { name: "K", include: false, checked: false },
  { name: "L", include: false, checked: false },
  { name: "M", include: false, checked: false },
  { name: "N", include: false, checked: false },
  { name: "O", include: false, checked: false },
  { name: "P", include: false, checked: false },
  { name: "Q", include: false, checked: false },
  { name: "R", include: false, checked: false },
  { name: "S", include: false, checked: false },
  { name: "T", include: false, checked: false },
  { name: "U", include: false, checked: false },
  { name: "V", include: false, checked: false },
  { name: "W", include: false, checked: false },
  { name: "X", include: false, checked: false },
  { name: "Y", include: false, checked: false },
  { name: "Z", include: false, checked: false }
];
